import { Router } from 'express'
import { authenticate, optionalAuth } from '../middleware/auth.js'
import { makeId } from '../utils/auth.js'
import { createNotification } from '../services/notifications.js'

const router = Router(); const PLATFORM_OWNER_EMAIL = 'oak79095@gmail.com'
async function counts(db, id) {
  const [followers, following, listings] = await Promise.all([db.one('SELECT COUNT(*) AS c FROM follows WHERE following_id = ?', [id]), db.one('SELECT COUNT(*) AS c FROM follows WHERE follower_id = ?', [id]), db.one("SELECT COUNT(*) AS c FROM listings WHERE user_id = ? AND status IN ('active', 'expired')", [id])])
  return { followers: Number(followers?.c || 0), following: Number(following?.c || 0), listings: Number(listings?.c || 0) }
}
router.get('/friend-requests', authenticate, async (req, res, next) => { try { res.json(await req.app.locals.database.many("SELECT fr.id, fr.status, fr.created_at, u.id AS user_id, u.name, u.avatar FROM friend_requests fr JOIN users u ON u.id = fr.sender_id WHERE fr.recipient_id = ? AND fr.status = 'pending' ORDER BY fr.created_at DESC", [req.user.id])) } catch (error) { next(error) } })
router.get('/:id', optionalAuth, async (req, res, next) => { try { const db = req.app.locals.database; const u = await db.one('SELECT id, name, email, avatar, verified, created_at FROM users WHERE id = ?', [req.params.id]); if (!u) return res.status(404).json({ error: 'غير موجود' }); const c = await counts(db, u.id); const is_me = req.user?.id === u.id; const is_following = !is_me && req.user ? Boolean(await db.one('SELECT 1 FROM follows WHERE follower_id = ? AND following_id = ?', [req.user.id, u.id])) : false; let friend_status = 'none'; if (!is_me && req.user) { const r = await db.one('SELECT status, sender_id FROM friend_requests WHERE (sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?) ORDER BY created_at DESC LIMIT 1', [req.user.id, u.id, u.id, req.user.id]); if (r?.status === 'accepted') friend_status = 'accepted'; else if (r?.status === 'pending') friend_status = r.sender_id === req.user.id ? 'sent' : 'received' } res.json({ id: u.id, name: u.name, avatar: u.avatar || null, created_at: u.created_at, verified: Boolean(u.verified), is_platform_owner: u.email?.toLowerCase() === PLATFORM_OWNER_EMAIL, ...c, is_following, friend_status, is_me }) } catch (error) { next(error) } })
router.post('/:id/follow', authenticate, async (req, res, next) => { try { const db = req.app.locals.database; const target = await db.one('SELECT id FROM users WHERE id = ?', [req.params.id]); if (!target) return res.status(404).json({ error: 'غير موجود' }); if (target.id === req.user.id) return res.status(400).json({ error: 'لا يمكنك متابعة نفسك' }); const existing = await db.one('SELECT id FROM follows WHERE follower_id = ? AND following_id = ?', [req.user.id, target.id]); let following; if (existing) { await db.run('DELETE FROM follows WHERE id = ?', [existing.id]); following = false } else { await db.run('INSERT INTO follows(id,follower_id,following_id) VALUES(?,?,?) ON CONFLICT (follower_id,following_id) DO NOTHING', [makeId(), req.user.id, target.id]); following = true; const actor = await db.one('SELECT name FROM users WHERE id = ?', [req.user.id]); await createNotification(db, { recipientId: target.id, actorId: req.user.id, type: 'follow', entityId: req.user.id, message: `${actor?.name || 'مستخدم'} بدأ بمتابعتك` }) } const followers = await db.one('SELECT COUNT(*) AS c FROM follows WHERE following_id = ?', [target.id]); res.json({ following, followers: Number(followers.c) }) } catch (error) { next(error) } })
router.post('/:id/friend-request', authenticate, async (req, res, next) => { try { const db = req.app.locals.database; const target = await db.one('SELECT id FROM users WHERE id = ?', [req.params.id]); if (!target) return res.status(404).json({ error: 'غير موجود' }); if (target.id === req.user.id) return res.status(400).json({ error: 'لا يمكنك إرسال طلب لنفسك' }); const existing = await db.one('SELECT * FROM friend_requests WHERE (sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?) ORDER BY created_at DESC LIMIT 1', [req.user.id, target.id, target.id, req.user.id]); if (existing?.status === 'accepted') return res.json({ status: 'accepted' }); if (existing?.status === 'pending') { if (existing.sender_id === req.user.id) { await db.run('DELETE FROM friend_requests WHERE id = ?', [existing.id]); return res.json({ status: 'none' }) } return res.json({ status: 'received' }) } const id = existing?.id || makeId(); if (existing) await db.run("UPDATE friend_requests SET status = 'pending', updated_at = CURRENT_TIMESTAMP WHERE id = ?", [id]); else await db.run('INSERT INTO friend_requests(id,sender_id,recipient_id) VALUES(?,?,?)', [id, req.user.id, target.id]); const actor = await db.one('SELECT name FROM users WHERE id = ?', [req.user.id]); await createNotification(db, { recipientId: target.id, actorId: req.user.id, type: 'friend_request', entityId: req.user.id, message: `${actor?.name || 'مستخدم'} أرسل لك طلب صداقة` }); res.status(201).json({ status: 'sent' }) } catch (error) { next(error) } })
router.post('/friend-requests/:id/respond', authenticate, async (req, res, next) => { try { const db = req.app.locals.database; const request = await db.one("SELECT * FROM friend_requests WHERE id = ? AND recipient_id = ? AND status = 'pending'", [req.params.id, req.user.id]); if (!request) return res.status(404).json({ error: 'طلب الصداقة غير موجود' }); if (req.body?.action === 'accept') { await db.run("UPDATE friend_requests SET status = 'accepted', updated_at = CURRENT_TIMESTAMP WHERE id = ?", [request.id]); await db.run('INSERT INTO follows(id,follower_id,following_id) VALUES(?,?,?) ON CONFLICT (follower_id,following_id) DO NOTHING', [makeId(), request.sender_id, request.recipient_id]); await db.run('INSERT INTO follows(id,follower_id,following_id) VALUES(?,?,?) ON CONFLICT (follower_id,following_id) DO NOTHING', [makeId(), request.recipient_id, request.sender_id]); await createNotification(db, { recipientId: request.sender_id, actorId: req.user.id, type: 'friend_accepted', entityId: req.user.id, message: 'تم قبول طلب الصداقة' }); return res.json({ status: 'accepted' }) } if (req.body?.action === 'reject') { await db.run("UPDATE friend_requests SET status = 'rejected', updated_at = CURRENT_TIMESTAMP WHERE id = ?", [request.id]); return res.json({ status: 'none' }) } res.status(400).json({ error: 'الإجراء غير صحيح' }) } catch (error) { next(error) } })
export default router
